from collections import defaultdict
from datetime import datetime
import pytz
from src.state import GraphState
from src.config import settings

def create_digest(state: GraphState) -> GraphState:
    if state.error:
        return state
    
    if not state.analyzed_emails:
        state.final_digest = "No emails were analyzed for yesterday."
        return state
        
    grouped = defaultdict(list)
    for e in state.analyzed_emails:
        grouped[e.category].append(e)

    # Category display order and icons
    category_config = {
        "Job Updates": "💼",
        "Careers": "🎯", 
        "Finance": "💰",
        "Marketing": "📢",
        "Social": "👋",
        "System": "⚙️",
        "Other": "📋"
    }
    
    # current date for header
    ist = pytz.timezone(settings.TIMEZONE)
    now = datetime.now(ist)
    date_str = now.strftime("%A, %B %d, %Y")
    
    total_emails = len(state.raw_emails)
    analyzed_count = len(state.analyzed_emails)
    
    digest = []
    digest.append("=" * 50)
    digest.append(f"📧 DAILY EMAIL SUMMARY")
    digest.append(f"📅 {date_str}")
    digest.append("=" * 50)
    digest.append("")
    digest.append(f"📊 Processed: {analyzed_count} of {total_emails} emails")
    digest.append("")
    
    # Count by category summary
    digest.append("📁 CATEGORIES:")
    for cat, icon in category_config.items():
        count = len(grouped.get(cat, []))
        if count > 0:
            digest.append(f"   {icon} {cat}: {count}")
    digest.append("")
    digest.append("-" * 50)
    
    # Detailed breakdown by category
    for category, icon in category_config.items():
        emails = grouped.get(category, [])
        if not emails:
            continue
            
        digest.append("")
        digest.append(f"{icon} {category.upper()} ({len(emails)})")
        digest.append("-" * 30)
        
        emails.sort(key=lambda x: x.importance, reverse=True)
        
        for e in emails:
            if e.importance >= 4:
                priority = "🔴 HIGH"
            elif e.importance == 3:
                priority = "🟡 MED"
            else:
                priority = "🟢 LOW"
            
            digest.append("")
            digest.append(f"  [{priority}] {e.subject}")
            digest.append(f"  From: {e.sender}")
            digest.append("")
            
            # Summary points
            for i, point in enumerate(e.summary_points, 1):
                digest.append(f"    • {point}")
            
            digest.append("")
    
    digest.append("")
    digest.append("=" * 50)
    digest.append("Generated by Email Summarizer Agent")
    digest.append("=" * 50)

    state.final_digest = "\n".join(digest)
    return state
